name: execo66:tests

on:
  push:
    branches: [master, github/workflows]
    paths-ignore:
      - "**.md"
      - "**/.vscode"
      - "**/.air.toml"
      - "specs/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "**/.vscode"
      - "**/.air.toml"
      - "specs/**"

jobs:
  query-tests:
    name: query-tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: execo_testing
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          touch ./config/.env.dev
          echo TEST_PSQL_CONN_STRING="postgres://postgres:postgres@localhost:5432/execo_testing?sslmode=disable" >> ./config/.env.dev
          cat ./config/.env.dev
      - name: Install golang-migrate
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.15.1
          which migrate
      - name: Run migrations
        run: make migrate-test-db
      - name: Seed database
        run: make seed-querytestdata
      - name: Run tests
        run: make test-queries
